application: rf-lm-poc
#application: razorfish-prototype-1
version: 1-10
#version: 1-1
runtime: python
api_version: 1  

default_expiration: "2d"

builtins:
- deferred: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static
- url: /geocodeworker
  script: main.py
- url: /hotelsworker
  script: main.py
- url: /hotelspriceworker
  script: main.py
- url: /.*
  script: main.py