application: rf-lm-poc
#application: razorfish-prototype-1
version: 1-8
#version: 1-1
runtime: python
api_version: 1  

default_expiration: "10d"

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static
    
- url: /.*
  script: main.py
