application: rf-lm-poc
#application: razorfish-prototype-1
version: 1-9
#version: 1-1
runtime: python
api_version: 1  

default_expiration: "0d"

builtins:
- deferred: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static
- url: /geocodeworker
  script: main.py
- url: /hotelsworker
  script: main.py
  login: admin
- url: /.*
  script: main.py
  
# OAuth request page
- url: /admin/authorize_prediction
  script: oauth_requester.py
  login: admin

# OAuth callback handler
- url: /admin/authorize_prediction/auth_callback
  script: oauth_callback.py
  login: admin