#application: rf-lm-poc
application: razorfish-prototype-1
version: 1-13
#application: razorfish-hotels
#version: 1-14
runtime: python
api_version: 1  

default_expiration: "0d"

builtins:
- deferred: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static
- url: /geocodeworker
  script: main.py
- url: /hotelsworker
  script: main.py
- url: /hotelspriceworker
  script: main.py
- url: /.*
  script: main.py